### ISSUE TITLE
The index page is displayed incorrectly on a mobile phone

### ISSUE THREAD

**Issue by danscodelab** [Pinpoint-Simulations/website#4]
### **Issue:**

- The mobile view is broken because the two images "ouroboros.svg" and "horizonicon.png" do not scale on the mobile view

### **How to reproduce the issue:**

- Simply open the website on a mobile phone

**Comment by scoopscode** [comment]
We already know about this and we are working on a solution as soon as we can.

**Comment by Megabrains44** [comment]
Yeah, the image scaling is making it weird on mobile, if we scale that down for mobile optimization, it should look normal again.

**Comment by Megabrains44** [comment]
Alright, since the images are removed, it should scale properly now. (Not optimized for mobile 100% yet.)
